import {CARDS,HEROES} from '/shared/cards.js';
import {BATTLE_LEVELS} from '/shared/battle-design.js';
import {combatAttack} from '/shared/engine.js';
import {CODEX,QUICK_RULES,cardTerms} from '/shared/codex.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const panel=document.createElement('dialog');panel.className='combat-rpg-panel';panel.setAttribute('aria-label','Ficha de aventura da mesa');document.body.append(panel);
let state,drawCard,seat,unitId=null,source=null,hideTimer;
document.addEventListener('bloodmoon-dismiss-peeks',()=>{if(panel.open&&!panel.matches(':modal'))panel.close();});
export function syncCombatRpg(room,cardHTML){
 state=room;drawCard=cardHTML;
 if(!room||room.phase==='finished'){panel.close();return;}
 const controls=document.querySelector('.arena .corner-controls');
 if(controls&&!controls.querySelector('[data-rpg-open]'))controls.insertAdjacentHTML('beforeend','<button class="icon-button" data-rpg-open aria-label="Ficha RPG: níveis, atributos e equipamentos" title="Ficha de aventura">♜</button>');
 if(panel.open)paint();
}
function paint(){
 if(!state)return;const player=state.players[seat??state.seat],units=Object.values(player.lanes).flat(),unit=units.find(u=>u.uid===unitId),hero=!unit,c=unit&&CARDS[unit.cardId],level=hero?player.battleLevel||1:unit.level||1,xp=hero?player.battleXP||0:unit.battleXP??((unit.kills||0)*2),steps=hero?BATTLE_LEVELS:[0,2,6],base=steps[level-1]||0,next=steps[level],pct=next?Math.min(100,100*Math.max(0,xp-base)/(next-base)):100,gear=hero?player.heroGear||[]:unit.gearItems||[],name=hero?HEROES[player.faction]?.name||'Líder':c.name;
 panel.innerHTML=`<header><span>♜</span><div><small>AVENTURA DESTA PARTIDA</small><h3>${esc(name)}</h3></div><button data-rpg-close aria-label="Fechar ficha RPG">×</button></header><nav aria-label="Escolher combatente"><button data-rpg-unit="" aria-pressed="${hero}">♛ LÍDER</button>${units.map(u=>`<button data-rpg-unit="${u.uid}" aria-pressed="${u.uid===unitId}">${esc(CARDS[u.cardId].name)}</button>`).join('')}</nav><div class="rpg-vitals"><div class="rpg-level-medal"><b>${level}</b><small>NÍVEL</small></div><div class="rpg-xp"><div><b>${next?`${xp} / ${next} XP`:'NÍVEL MÁXIMO'}</b><small>${hero?'ABATES +1 · CONQUISTAS +2':'ABATES +2 · CONQUISTAS +1'}</small></div><meter min="0" max="100" value="${pct}" aria-label="Progresso de nível">${pct}%</meter><small>${next?hero?['','Próximo: +2 vida','Próximo: +2 Suprimentos','Próximo: +1 Favor e +1 Cerco'][level]:'Próximo: +1 ataque e +2 vida':'Sua evolução permanece até o fim desta partida.'}</small></div></div><div class="rpg-attributes"><span><i>♥</i><b>${Math.max(0,hero?player.health:unit.health)}<small>/${hero?player.maxHealth:unit.maxHealth||c.health}</small></b><small>VIDA</small></span><span><i>⚔</i><b>${hero?'+'+(player.heroAttackBonus||0):combatAttack(unit)}</b><small>${hero?'BÔNUS DE HABILIDADE':'ATAQUE ATUAL'}</small></span><span><i>♜</i><b>${hero?player.renown||0:(unit.influence||0)+(unit.tempInfluence||0)}</b><small>${hero?'RENOME':'INFLUÊNCIA'}</small></span></div>${unit?`<div class="rpg-status">${unit.ready?'⚔ PRONTO PARA ATACAR':'◷ EXAUSTO'}${unit.bleed?` · ≋ ${unit.bleed} SANGRAMENTO`:''}</div><div class="rpg-keywords">${cardTerms(c).map(k=>`<p><b>${CODEX[k][1]} ${CODEX[k][0]}</b><span>${esc(QUICK_RULES[k]||CODEX[k][3])}</span></p>`).join('')}</div>`:''}<h4>RELÍQUIAS EQUIPADAS <small>${gear.length}/${hero?1:2}</small></h4><div class="rpg-gear">${gear.map(g=>`<article>${drawCard(g.cardId)}<p>${esc(CARDS[g.cardId]?.text)}</p></article>`).join('')}${Array.from({length:Math.max(0,(hero?1:2)-gear.length)},()=>'<div class="rpg-empty"><b>◇</b><span>ESPAÇO LIVRE</span><small>Jogue uma carta de equipamento neste aliado.</small></div>').join('')}</div><footer>Níveis e bônus da mesa reiniciam na próxima partida. A peça persistente continua sujeita ao desgaste.</footer>`;
}
function open(button,modal){if(!state)return;clearTimeout(hideTimer);source=button;seat=Number(button.dataset.rpgSeat??state.seat);unitId=null;paint();if(!panel.open){if(modal)panel.showModal();else panel.show();}}
document.addEventListener('click',event=>{const b=event.target.closest('[data-rpg-open]');if(!b)return;event.preventDefault();event.stopImmediatePropagation();if(panel.open)panel.close();open(b,true);},true);
document.addEventListener('pointerover',event=>{const b=event.target.closest('[data-rpg-open]');if(event.pointerType==='mouse'&&b&&!panel.matches(':modal'))open(b,false);});
document.addEventListener('pointerout',event=>{if(event.target.closest('[data-rpg-open]')&&!panel.matches(':modal'))hideTimer=setTimeout(()=>panel.close(),350);});
panel.addEventListener('pointerenter',()=>clearTimeout(hideTimer));panel.addEventListener('pointerleave',()=>{if(!panel.matches(':modal'))hideTimer=setTimeout(()=>panel.close(),350);});
panel.addEventListener('click',event=>{if(event.target.closest('[data-rpg-close]')){panel.close();source?.isConnected&&source.focus();}const b=event.target.closest('[data-rpg-unit]');if(b){unitId=b.dataset.rpgUnit||null;paint();}const gear=event.target.closest('.rpg-gear .game-card');if(gear){const article=gear.closest('article');article.classList.toggle('expanded');gear.setAttribute('aria-expanded',String(article.classList.contains('expanded')));}});
panel.addEventListener('keydown',event=>event.stopPropagation());
