import {CARDS,LANES} from '/shared/cards.js';
import {ORDERS,AVATAR_IDS,ORIGINS,BATTLE_LEVELS} from '/shared/battle-design.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function characterUI(profile,{onboarding=false}={}){
 const avatar=profile.character?.avatar||'vesper',origin=profile.character?.origin||'exile';
 return `<form id="character-form" class="character-forge" data-onboarding="${onboarding}"><div class="character-stage-art"><img data-character-portrait src="/assets/avatars/${avatar}.png" alt="Retrato escolhido"><span>SEU NOME NA NOITE</span></div><div class="character-options"><small>UM VIAJANTE · DUAS LINHAGENS</small><h3>Sele seu juramento</h3><label>Nome do personagem<input name="name" maxlength="24" minlength="2" required value="${esc(profile.name==='Caçador'?'':profile.name)}" autocomplete="nickname"></label><fieldset><legend>Seu retrato</legend><div class="character-portraits">${AVATAR_IDS.map(id=>`<label><input type="radio" name="avatar" value="${id}" ${id===avatar?'checked':''}><img src="/assets/avatars/${id}.png" alt="${id}"></label>`).join('')}</div></fieldset><fieldset><legend>Sua origem</legend>${Object.entries(ORIGINS).map(([id,o])=>`<label class="origin-choice"><input type="radio" name="origin" value="${id}" ${id===origin?'checked':''}><span><b>${o.name}</b><small>${o.text}</small><em>“${o.oath}”</em></span></label>`).join('')}</fieldset><p>Origem e retrato definem sua identidade. Você pode usar os dois decks e mudar sua aparência sem custo.</p><button class="hunt-button" type="submit"><span>${onboarding?'INICIAR MINHA HISTÓRIA':'SALVAR PERSONAGEM'}</span></button></div></form>`;
}
export function loadoutUI(profile,deckId,slot,cardHTML){
 const deck=profile.decks.find(d=>d.id===deckId)||profile.decks.find(d=>d.id===profile.activeDecks?.[profile.selectedFaction||profile.starterFaction])||profile.decks[0];
 if(!deck)return '<p>Crie seu primeiro deck para preparar equipamentos.</p>';
 const items=profile.items||[],ids=[...new Set(items.filter(i=>i.durability>0&&!i.listingId&&['neutral',deck.faction].includes(CARDS[i.cardId]?.faction)).map(i=>i.cardId))],gear=deck.cards.filter(id=>CARDS[id]?.type==='equipment').length;
 return `<div class="loadout-banner"><span>⚒</span><div><small>PREPARAÇÃO DA AVENTURA</small><h3>${esc(deck.name)}</h3><p>${gear}/6 equipamentos · ${deck.cards.length}/20 cartas. Selecione uma posição e depois a peça que ocupará seu lugar.</p></div></div><nav class="loadout-decks">${profile.decks.map(d=>`<button data-loadout-deck="${d.id}" aria-pressed="${d.id===deck.id}">${esc(d.name)}</button>`).join('')}</nav><div class="loadout-layout"><section><h4>POSIÇÕES DO DECK</h4><div class="loadout-slots">${deck.cards.map((id,i)=>{const c=CARDS[id],reserve=(deck.autoRefills||[]).some(r=>r.replacementId===id);return `<button data-loadout-slot="${i}" data-loadout-id="${deck.id}" class="${slot===i?'chosen':''} ${c.type==='equipment'?'is-gear':''}"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(c.name)}<small>${reserve?'RESERVA · PODE REEQUIPAR':c.type==='equipment'?'EQUIPAMENTO':'ALIADO / RITUAL'}</small></span></button>`;}).join('')}</div></section><section><h4>RELÍQUIAS UTILIZÁVEIS</h4><div class="loadout-pool">${ids.map(id=>{const pieces=items.filter(i=>i.cardId===id&&i.durability>0&&!i.listingId),copies=deck.cards.filter(x=>x===id).length;return `<article>${cardHTML(id)}<span>${pieces.length} PEÇA(S) · ${copies} NO DECK</span><small>DURABILIDADE ${pieces.map(i=>i.durability+'/'+i.maxDurability).join(' · ')}</small><button data-loadout-equip="${id}" data-loadout-id="${deck.id}" ${slot===null?'disabled':''}>EQUIPAR NA POSIÇÃO ${slot===null?'—':slot+1}</button></article>`;}).join('')||'<p>Nenhuma peça utilizável. Seu deck pode jogar com reservas; obtenha itens em expedições ou repare no Relicário.</p>'}</div><button class="menu-option" data-modal="market">⚒ REPARAR / CRIAR EQUIPAMENTOS</button></section></div>`;
}
export function battleGuide(me){return `<div class="battle-codex"><p><b>Poder de conquista:</b> Corte soma influência; Catacumbas e Caçada somam ataque. +Poder soma apenas à disputa da frente até o confronto; não aumenta dano. Sobreviventes são contados após golpes automáticos e sangramento. Empate não premia.</p><div class="campaign-fronts">${LANES.map(l=>`<article><i>${l.icon}</i><h3>${l.name}</h3><p>${l.reward}</p><small>${l.id==='court'?'1 Favor, ou 2 ao vencer por 2+ poder · limite 5':l.id==='crypt'?'2 Suprimentos · limite 6':'1 Cerco · limite 3'}</small>${Object.entries(ORDERS).filter(([,o])=>o.category===l.id).map(([id,o])=>`<div><b>${o.name} · ${o.cost}</b><p>${o.text}</p></div>`).join('')}</article>`).join('')}</div><p>Uma ordem por frente por rodada. Cada ordem gasta sua ação e passa a vez ao rival. Os pontos ficam até serem gastos; encerrada a partida, zeram.</p><div class="battle-level-path">${BATTLE_LEVELS.map((xp,i)=>`<span class="${(me?.battleLevel||1)>=i+1?'earned':''}"><b>NÍVEL ${i+1}</b><small>${xp} XP</small>${['Início da aventura','+2 vida máxima e atual','+2 Suprimentos','+1 Favor e +1 Cerco'][i]}</span>`).join('')}</div><p>Líder: +1 XP por abate rival e +2 por conquista. Criaturas: +2 XP por abate direto sobrevivido e +1 por conquistar uma frente; níveis 2/3 em 2/6 XP, cada nível dá +1 ataque e +2 vida. Tudo reinicia a cada partida.</p></div>`;}
export function playMotionScene({title='Véspera',text='',portrait='oracle',board='court-board',ending=false}={}){
 return new Promise(resolve=>{
  const previous=document.activeElement,el=document.createElement('section');el.className='motion-scene';el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.setAttribute('aria-label',title);
  el.innerHTML=`<img class="motion-landscape" src="/assets/world/${board}.png" alt=""><div class="motion-haze"></div><img class="motion-person" src="/assets/avatars/${portrait}.png" alt=""><div class="motion-letterbox"></div><div class="motion-dialogue"><small>${ending?'UM JURAMENTO CUMPRIDO':'CRÔNICAS DE VÉSPERA'}</small><h2>${esc(title)}</h2><p>${esc(text)}</p></div><button class="motion-continue">CONTINUAR ↗</button>`;
  const close=()=>{el.remove();document.removeEventListener('keydown',key,true);previous?.isConnected&&previous.focus();resolve();};const key=e=>{e.stopImmediatePropagation();if(['Escape','Enter',' '].includes(e.key)){e.preventDefault();close();}if(e.key==='Tab'){e.preventDefault();el.querySelector('button').focus();}};
  document.body.append(el);el.querySelector('button').addEventListener('click',close);el.querySelector('button').focus();document.addEventListener('keydown',key,true);
 });
}
