import {AVATARS} from '/shared/realms.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let building='camp',chronicle='story',council='council',owner=null;
const BUILDINGS={camp:{name:'Acampamento',glyph:'⌂',asset:'lantern',title:'Um lugar para regressar',text:'Amplie seus estoques de provisões e reúna mais materiais em cada coleta.'},forge:{name:'Forja do Juramento',glyph:'⚒',asset:'anvil',title:'Ferro, fogo e memória',text:'Transforme minério em sucata e forje equipamentos persistentes para suas expedições.'},library:{name:'Arquivo do Véu',glyph:'✧',asset:'ledger',title:'O poder dos nomes',text:'Converta essências em fragmentos para criar as cartas que faltam à sua coleção.'}};
function buildingDetail(data,busy){const p=data.player,id=building,b=BUILDINGS[id],lv=p.holdings[id],gold=20*(lv+1),wood=4*(lv+1),ore=3*(lv+1),max=lv>=5,poor=data.profile.coins<gold||p.materials.timber<wood||p.materials.ore<ore,blocked=busy||p.activeRoom;const action=id==='forge'?'refine':'study',resource=id==='forge'?'ore':'essence',refineYield=4+lv+(p.adventure?.talents?.artisan||0)*2;return `<div class="rs-building-title"><small>DOMÍNIO PERSISTENTE</small><h2>${b.name}</h2><span>${'◆'.repeat(lv)}${'◇'.repeat(5-lv)} <b>${lv}/5</b></span></div><h3>${b.title}</h3><p>${b.text}</p><div class="rs-benefit">${id==='camp'?`<span>◉ <b>${20+lv*5}</b><small>CAPACIDADE DE PROVISÕES</small></span><span>♧ <b>${2+lv+(p.adventure?.talents?.scout||0)}</b><small>MATERIAIS POR COLETA</small></span>`:`<span>${b.glyph}<b>${id==='forge'?refineYield:6+lv*2}</b><small>${id==='forge'?'SUCATA POR REFINO':'FRAGMENTOS POR ESTUDO'}</small></span><span>✧<b>${lv?'ATIVO':'SELADO'}</b><small>${lv?'SERVIÇO DISPONÍVEL':'CONSTRUA PARA LIBERAR'}</small></span>`}</div><button class="rs-upgrade" data-realm-upgrade="${id}" ${blocked||max||poor?'disabled':''}><span>${max?'CONSTRUÇÃO COMPLETA':lv?'↑ EVOLUIR PARA NÍVEL '+(lv+1):'⚒ CONSTRUIR'}</span><small>${max?'GRAU MÁXIMO':`${gold} MARCAS · ${wood} MADEIRA · ${ore} MINÉRIO`}</small></button>${poor&&!max?'<p class="rs-cost-note">Colete materiais e reúna Marcas na bolsa. Se estiverem no cofre, retire pelo Mercado antes de melhorar.</p>':''}${id==='camp'?`<button class="rs-service" data-realm-action="rest" ${blocked||data.profile.coins<10||p.provisions>=20+lv*5?'disabled':''}>◉ REABASTECER · 10 MARCAS<small>+${8+(p.adventure?.talents?.warden||0)*2} PROVISÕES</small></button>`:`<button class="rs-service" data-realm-action="${action}" ${blocked||!lv||data.profile.coins<5||p.materials[resource]<3?'disabled':''}>${id==='forge'?'⚒ REFINAR MINÉRIO':'✧ ESTUDAR ESSÊNCIAS'}<small>5 MARCAS · 3 ${id==='forge'?'MINÉRIOS':'ESSÊNCIAS'}</small></button>`}${id==='forge'?`<button class="rs-service" data-realm-action="forge-gear" ${blocked||!lv||data.profile.coins<(lv>=3?50:25)||p.materials.ore<(lv>=3?10:6)||p.materials.essence<2?'disabled':''}>♜ FORJAR RELÍQUIA ${lv>=3?'INCOMUM':'COMUM'}<small>${lv>=3?'50 MARCAS · 10 MINÉRIOS':'25 MARCAS · 6 MINÉRIOS'} · 2 ESSÊNCIAS</small></button>`:''}<button class="rs-return" data-realm-tab="map">↶ VOLTAR À EXPLORAÇÃO</button>`;}
export function domainScene(data,busy){return `<section class="rs-domain"><div class="rs-domain-land"><div class="rs-domain-fog"></div><div class="rs-domain-intro"><small>SEU DOMÍNIO</small><h2>O fogo permanece.</h2><p>Escolha uma construção para preparar a próxima jornada.</p></div><div class="rs-buildings">${Object.entries(BUILDINGS).map(([id,b],i)=>`<button class="rs-building ${building===id?'chosen':''} ${data.player.holdings[id]?'built':'unbuilt'}" data-rs-building="${id}" aria-pressed="${building===id}" style="--order:${i}"><div class="rs-building-halo"></div><img src="/assets/market/${b.asset}.png" alt=""><i>${b.glyph}</i><span>${b.name}</span><small>${data.player.holdings[id]?'GRAU '+data.player.holdings[id]:'AGUARDA CONSTRUÇÃO'}</small></button>`).join('')}</div><details class="rs-avatar-drawer"><summary>♟ RETRATO DO VIAJANTE</summary><div>${AVATARS.map(id=>`<button data-realm-avatar="${id}" class="${data.player.avatar===id?'active':''}" aria-label="Escolher retrato ${id}"><img src="/assets/avatars/${id}.png" alt="${id}"></button>`).join('')}</div></details></div><aside class="rs-building-detail">${buildingDetail(data,busy)}</aside></section>`;}
let pending=null;
export function realmSanctum(data,tab,content,busy=false){if(owner!==data.player.publicId){owner=data.player.publicId;building='camp';chronicle='story';council='council';}pending={data,tab,busy};return `<main class="realm-sanctum rs-${tab}" aria-label="${tab==='camp'?'Seu domínio':tab==='house'?'Conselho das Casas':'Crônicas de Véspera'}"><div class="rs-scene"></div><header class="rs-header"><button data-realm-tab="map" class="rs-back">↶<span>REINOS<small>VOLTAR AO MUNDO</small></span></button><div><small>BLOODMOON · VÉSPERA</small><h1>${tab==='camp'?'Seu domínio':tab==='house'?'O conselho da noite':'A crônica do seu juramento'}</h1></div><nav>${[['camp','⚒','Domínio'],['house','♜','Casas'],['journey','✧','Crônica']].map(([id,i,label])=>`<button data-realm-tab="${id}" class="${id===tab?'active':''}"><i>${i}</i><span>${label}</span></button>`).join('')}</nav><div class="rs-wallet"><span>◈ <b>${data.profile.coins}</b><small>MARCAS</small></span>${Object.entries({timber:['♧','MADEIRA'],ore:['⬡','MINÉRIO'],essence:['✧','ESSÊNCIA']}).map(([id,[icon,name]])=>`<span>${icon} <b>${data.player.materials[id]}</b><small>${name}</small></span>`).join('')}</div></header>${tab==='camp'?domainScene(data,busy):`<div class="rs-inner"><nav class="rs-pages">${(tab==='journey'?[['story','✧','Crônica'],['talents','☾','Talentos & comissão'],['stories','◇','Histórias'],['expedition','⚔','Expedição'],['legacy','♛','Legado']]:[['council','♜','Conselho'],['houses','⚑','Estandartes'],['news','≋','Guerras & notícias']]).map(([id,i,label])=>`<button data-rs-page="${id}" aria-pressed="${(tab==='journey'?chronicle:council)===id}"><i>${i}</i><span>${label}</span></button>`).join('')}</nav><div class="rs-content">${content}</div></div>`}<footer class="rs-footer"><span>✧ ${esc(data.profile.name)} · EXPLORADOR ${data.player.level}</span><button data-modal="market">⚖ MERCADO</button><button data-modal="loadout">⚔ PREPARAR DECK</button></footer></main>`;}
let mounted=null;
function mount(){const root=document.querySelector('.realm-sanctum');if(!root||mounted===root||!pending)return;mounted=root;const {data,tab,busy}=pending;
 const sections=()=>{const selected=tab==='journey'?chronicle:council;root.querySelectorAll('[data-rs-page]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.rsPage===selected)));if(tab==='journey'){const body=root.querySelector('.adventure-workspace');for(const child of body?.children||[]){let group='story';if(child.matches('.adventure-systems'))group='talents';else if(child.matches('.side-stories'))group='stories';else if(child.matches('.expedition-council'))group='expedition';else if(child.matches('.legacy-board,.personal-journal'))group='legacy';child.hidden=group!==selected;}}else if(tab==='house'){const body=root.querySelector('.houses-workspace');for(const child of body?.children||[]){const group=child.matches('.house-list')?'houses':child.matches('.realm-war-log')?'news':'council';child.hidden=group!==selected;}}};sections();
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.rsBuilding){building=b.dataset.rsBuilding;root.querySelectorAll('[data-rs-building]').forEach(el=>{el.classList.toggle('chosen',el.dataset.rsBuilding===building);el.setAttribute('aria-pressed',String(el.dataset.rsBuilding===building));});root.querySelector('.rs-building-detail').innerHTML=buildingDetail(data,busy);}
 if(b.dataset.rsPage){if(tab==='journey')chronicle=b.dataset.rsPage;else council=b.dataset.rsPage;sections();root.querySelector('.rs-content').scrollTop=0;}
 });
}
new MutationObserver(mount).observe(document.querySelector('#app'),{childList:true,subtree:true});
