import {CARDS} from '/shared/cards.js';
import {ECONOMY} from '/shared/progression.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let zone='inventory',page=0,selected=null,filter='all';
let orders=[];
export function setPurchaseOrders(value){orders=value||[];}
export function marketNavigation(button){
 if(button.dataset.tradeZone){zone=button.dataset.tradeZone;page=0;selected=null;filter='all';return true;}
 if(button.dataset.tradeSelect){selected=button.dataset.tradeSelect;return true;}
 if(button.dataset.tradePage){page=Math.max(0,page+Number(button.dataset.tradePage));selected=null;return true;}
 if(button.dataset.tradeFilter){filter=button.dataset.tradeFilter;page=0;selected=null;return true;}
 return false;
}
export function tradingHall(profile,items,offers,card){
 const vault=profile.vault||{balance:0,version:0},zones=[['vault','◈','Cofre'],['market','⚖','Comércio'],['orders','▧','Encomendas'],['inventory','♜','Relicário'],['forge','⚒','Forja']];
 const pool=zone==='orders'?orders.map(o=>({...o,rarity:CARDS[o.cardId]?.rarity,durability:3,maxDurability:3})):zone==='market'?offers:zone==='forge'?Object.values(CARDS).filter(c=>c.type==='equipment').map(c=>({id:c.id,cardId:c.id,rarity:c.rarity,durability:3,maxDurability:3})):items;
 const filtered=pool.filter(i=>filter==='all'||filter==='repair'&&i.durability<i.maxDurability||filter==='trade'&&!i.bound&&!i.listingId&&!i.locked&&i.durability>0||filter===i.rarity);
 page=Math.min(page,Math.max(0,Math.ceil(filtered.length/6)-1));
 const visible=filtered.slice(page*6,page*6+6),key=i=>i.listingId&&zone==='market'?i.listingId:i.id;
 const item=visible.find(i=>key(i)===selected)||visible[0],c=item&&CARDS[item.cardId];
 const pieces=(profile.items||[]).filter(i=>i.durability>0&&!i.listingId).length;
 const header=`<header class="trade-hud"><div><small>MERCADO DO CREPÚSCULO</small><h2>Mercado do Crepúsculo</h2></div><div class="trade-balances"><span>◈ <b>${profile.coins||0}</b><small>BOLSA · DISPONÍVEL</small></span><span>▣ <b>${vault.balance||0}</b><small>COFRE · RESERVA</small></span><span>◈ <b>${(profile.coins||0)+(vault.balance||0)}</b><small>TOTAL DE MARCAS</small></span><span>⚒ <b>${profile.scrap||0}</b><small>SUCATA</small></span></div></header>`;
 const nav=`<nav class="trade-landmarks" aria-label="Locais do mercado">${zones.map(([id,icon,name])=>`<button data-trade-zone="${id}" aria-pressed="${zone===id}"><i>${icon}</i><b>${name}</b><small>${id==='vault'?'GUARDAR / RETIRAR':id==='market'?offers.length+' ANÚNCIOS':id==='orders'?orders.length+' PEDIDOS':id==='inventory'?pieces+' UTILIZÁVEIS':'CRIAR RELÍQUIAS'}</small></button>`).join('')}</nav>`;
 const guidance={inventory:['SUAS RELÍQUIAS','Escolha uma peça para preparar, reparar ou vender.'],market:['COMPRAR DE JOGADORES','Preço em Marcas da bolsa. Cada oferta entrega uma peça real.'],orders:['PEDIDOS DE COMPRA','Atenda pedidos com peças livres ou acompanhe suas encomendas.'],forge:['CRIAR EQUIPAMENTOS','Marcas + Sucata se tornam uma peça nova.'],vault:['GUARDAR RECOMPENSAS','Deposite suas Marcas ou retire para preparar a próxima aventura.']}[zone];
 const wayfinding=`<div class="trade-wayfinding"><b>${guidance[0]}</b><span>${guidance[1]}</span></div>`;
 const bank=`<section class="vault-chamber"><div class="vault-treasure"><header><small>SEU TESOURO</small><strong>${vault.balance||0}<span>MARCAS NO COFRE</span></strong></header><canvas data-vault-physics data-owner="${esc(profile.id)}" data-balance="${vault.balance||0}" tabindex="0" aria-label="Recipiente de moedas interativas. Arraste com mouse ou toque. Enter agita as moedas sem alterar o saldo."></canvas><small class="vault-touch-hint">✧ PEGUE · ARRASTE · SOLTE <span>Moedas ilustram o saldo; não equivalem a 1 Marca cada.</span></small></div><div class="vault-console"><small>BOLSA ⇄ COFRE</small><h3>Suas Marcas, prontas para a aventura.</h3><div class="vault-transfer-balances"><span>BOLSA · DISPONÍVEL<b>${profile.coins||0}</b></span><i>⇄</i><span>COFRE · RESERVA<b>${vault.balance||0}</b></span></div><label>Quantidade em Marcas<input id="vault-amount" type="number" min="1" step="1" inputmode="numeric" value="${Math.min(100,profile.coins||vault.balance||1)}"></label><div class="vault-quick-amounts">${[25,100,500].map(n=>`<button data-vault-amount="${n}">${n}</button>`).join('')}</div><div><button data-bank-action="deposit" ${!profile.coins?'disabled':''}>↓ DEPOSITAR</button><button data-bank-action="withdraw" ${!vault.balance?'disabled':''}>↑ RETIRAR</button></div><small>Todas as compras usam Marcas da bolsa. Retire a reserva do cofre antes de gastar. Transferências sem taxas.</small><details><summary>ÚLTIMOS MOVIMENTOS</summary>${(vault.history||[]).slice(0,5).map(e=>`<p>${e.direction==='deposit'?'↓ Guardado':'↑ Retirado'} · ${e.amount} Marcas</p>`).join('')||'<p>Nenhum movimento ainda.</p>'}</details></div></section>`;
 let actions='';
 if(item&&zone==='orders'){
  const deliverable=items.find(i=>i.cardId===item.cardId&&!i.bound&&!i.locked&&!i.listingId&&i.durability>0&&i.durability===i.maxDurability),tax=Math.floor(item.price*ECONOMY.marketTaxPercent/100);
  actions=`<span class="trade-ask">◈ ${item.price}<small>PAGAMENTO JÁ RESERVADO</small></span><p>Entregue uma peça com durabilidade máxima. Comprador: ${esc(item.buyerName)}.</p>${item.mine?`<button data-order-cancel="${item.id}">CANCELAR · DEVOLVER ${item.price} À BOLSA</button>`:`<button data-order-fill="${item.id}" data-order-item="${deliverable?.id||''}" ${deliverable?'':'disabled'}>ENTREGAR · RECEBER ${item.price-tax} MARCAS</button><small>Imposto: ${tax} Marcas. ${deliverable?'A peça sai do seu inventário e vai para o comprador.':'Você precisa de uma peça livre, negociável e totalmente reparada.'}</small><button data-trade-zone="forge">VER FORJA</button>`}`;
 }
 if(item&&zone==='market')actions=item.mine?`<button data-market-cancel="${esc(item.listingId)}">RETIRAR ANÚNCIO</button>`:`<span class="trade-ask">◈ ${item.price}<small>PREÇO TOTAL</small></span><button class="gold-button" data-market-buy="${esc(item.listingId)}" ${profile.coins<item.price?'disabled':''}>COMPRAR RELÍQUIA</button>${profile.coins<item.price?`<button data-trade-zone="vault" data-withdraw-amount="${item.price-profile.coins}">RETIRAR ${item.price-profile.coins} MARCAS DO COFRE</button>`:''}<small>Vendedor: ${esc(item.sellerName)}</small>`;
 if(item&&zone==='forge'){const cost=ECONOMY.craftGear[c.rarity];actions=`<div class="forge-recipe"><span>◈ ${cost.coins}<small>MARCAS</small></span><b>＋</b><span>⚒ ${cost.scrap}<small>SUCATA</small></span><b>➜</b><span>◇ 1<small>PEÇA NOVA</small></span></div><button class="gold-button" data-craft="${c.id}" ${profile.coins<cost.coins||profile.scrap<cost.scrap?'disabled':''}>FORJAR EQUIPAMENTO</button><small>Ganha uma peça persistente com ${ECONOMY.gearDurability} usos.</small><details class="trade-order-create"><summary>ENCOMENDAR DE UM JOGADOR</summary><label>Oferta em Marcas<input id="order-price" type="number" min="5" max="5000" value="${cost.coins+cost.scrap}" inputmode="numeric"></label><button data-order-create="${c.id}">RESERVAR PAGAMENTO E PUBLICAR</button><small>Uma peça totalmente reparada. Máximo 3 encomendas. O valor sai da bolsa agora e volta se cancelar.</small></details>`;}
 if(item&&zone==='inventory'){
  const cost=(ECONOMY.repairCost[item.rarity]||12)*Math.max(0,item.maxDurability-item.durability),price=Math.max(5,c.cost*30);
  actions=`<button class="gold-button" data-modal="loadout">⚔ PREPARAR NO DECK</button>${item.durability<item.maxDurability?`<button data-repair="${esc(item.id)}" ${item.locked||item.listingId||profile.coins<cost?'disabled':''}>⚒ REPARAR · ${cost} MARCAS</button>`:''}${item.listingId?`<button data-market-cancel="${esc(item.listingId)}">RETIRAR ANÚNCIO</button>`:item.bound||item.locked||item.durability<=0?`<p>${item.bound?'⛓ Vinculado ao juramento: não pode ser vendido.':item.locked?'◷ Reservado para uma partida.':'⌁ Repare esta peça para poder anunciá-la.'}</p>`:`<label>Preço de venda<input data-item-price="${esc(item.id)}" type="number" min="5" max="5000" value="${price}" inputmode="numeric"></label><button data-market-list="${esc(item.id)}">⚖ ANUNCIAR NO MERCADO</button><small>Publicar: ${ECONOMY.marketListingFeePercent}% (mín. 1 Marca). Venda: ${ECONOMY.marketTaxPercent}% de imposto. O preço é definido por você.</small>`}`;
 }
 const stage=`<section class="trade-workspace"><div class="trade-shelves"><div class="trade-filter"><button data-trade-filter="all" aria-pressed="${filter==='all'}">TODOS</button>${zone==='inventory'?`<button data-trade-filter="repair" aria-pressed="${filter==='repair'}">⚒ REPARAR</button><button data-trade-filter="trade" aria-pressed="${filter==='trade'}">⚖ VENDÁVEIS</button>`:['common','uncommon','rare','epic','legendary'].map(r=>`<button data-trade-filter="${r}" aria-pressed="${filter===r}">${({common:'COMUM',uncommon:'INCOMUM',rare:'RARA',epic:'ÉPICA',legendary:'LENDÁRIA'})[r]}</button>`).join('')}</div><div class="trade-grid">${visible.map(i=>`<article class="trade-plinth ${key(i)===key(item)?'selected':''}">${card(i.cardId)}<button data-trade-select="${esc(key(i))}" aria-pressed="${key(i)===key(item)}"><b>${esc(CARDS[i.cardId].name)}</b><small>${['market','orders'].includes(zone)?'◈ '+i.price+' MARCAS':zone==='forge'?'⚒ VER RECEITA':i.durability<=0?'⌁ ESGOTADO':i.listingId?'⚖ ANUNCIADO':i.locked?'◷ RESERVADO':'◆ '+i.durability+'/'+i.maxDurability+' USOS'}</small></button></article>`).join('')||'<div class="trade-empty"><b>◇</b><h3>Nenhuma relíquia aqui.</h3><p>Explore Reinos para ganhar saques ou mude o filtro.</p><button data-open-realms>EXPLORAR VÉSPERA ↗</button></div>'}</div><div class="trade-pagination"><button data-trade-page="-1" ${page===0?'disabled':''} aria-label="Página anterior">❮</button><span>${page+1} / ${Math.max(1,Math.ceil(filtered.length/6))} · ${filtered.length} PEÇAS</span><button data-trade-page="1" ${(page+1)*6>=filtered.length?'disabled':''} aria-label="Próxima página">❯</button></div></div><aside class="trade-item-detail">${c?`<small>${zone==='forge'?'RECEITA DA FORJA':zone==='orders'?'ENCOMENDA DE JOGADOR':zone==='market'?'OFERTA DE JOGADOR':'SUA RELÍQUIA'}</small><h3>${esc(c.name)}</h3><div class="trade-item-stats"><span>⚔ +${c.attack}<small>ATAQUE</small></span><span>♥ +${c.health}<small>VIDA</small></span><span>◆ ${item.durability}/${item.maxDurability}<small>USOS</small></span></div><p>${esc(c.text)}</p><div class="trade-item-actions">${actions}</div>`:'<div class="trade-empty">⚖<p>A economia é movida pelos saques e anúncios dos jogadores.</p></div>'}</aside></section>`;
 return `<div class="trading-hall zone-${zone}"><div class="trade-scene" aria-hidden="true"></div><div class="trade-lantern" aria-hidden="true"></div>${header}${nav}${wayfinding}${zone==='vault'?bank:stage}<footer class="trade-route"><span>⚔ EXPLORE</span><i>›</i><span>◇ SAQUEIE</span><i>›</i><span>⚒ REPARE / FORJE</span><i>›</i><span>⚖ NEGOCIE</span><button data-open-realms>REINOS ↗</button><button data-modal="loadout">PREPARAR ↗</button></footer></div>`;
}
