import test from 'node:test';
import assert from 'node:assert/strict';
import {ensureFrontier,respawnDeposit,settlementAction} from '../shared/realm-frontier.js';
const now=1800000000000;
function fixture(){const regions=[{id:'home',kind:'sanctuary',x:10,y:50},{id:'wood',kind:'wilds',x:40,y:50,resource:'timber'}],world={houses:[{id:'a',name:'Casa A',leader:'p',faction:'vampire'}],wars:[]},w={actors:[],obstacles:[]};ensureFrontier(world,w,regions,now);const city=world.houses[0].settlement,p={realm:{publicId:'p',houseId:'a',materials:{timber:100,ore:100,essence:100},roaming:{x:city.x,y:city.y,energy:100,attackAt:0}}};return {regions,world,w,city,p};}
test('migration adds bounded deposits and physical cities once, preserving warehouse',()=>{const f=fixture();f.city.stock.timber=23;const ids=f.w.actors.map(a=>a.id);ensureFrontier(f.world,f.w,f.regions,now+100);assert.deepEqual(f.w.actors.map(a=>a.id),ids);assert.equal(f.w.actors.filter(a=>a.deposit).length,4);assert.ok(f.w.actors.some(a=>a.kind==='settlement'));assert.equal(f.city.stock.timber,23);const a=f.w.actors.find(a=>a.deposit);respawnDeposit(f.w,a,()=>.5);assert.ok(Math.hypot((a.x-a.deposit.x)*1.5,a.y-a.deposit.y)<=4);assert.equal(a.x,a.homeX);});
test('warehouse transfers conserve materials; outsiders cannot withdraw',()=>{const f=fixture();const act=input=>settlementAction(f.world,f.p,{houseId:'a',...input},now);act({operation:'deposit',resource:'ore'});assert.equal(f.p.realm.materials.ore,95);assert.equal(f.city.stock.ore,5);act({operation:'withdraw',resource:'ore'});assert.equal(f.p.realm.materials.ore,100);f.p.realm.houseId='b';assert.throws(()=>act({operation:'withdraw',resource:'ore'}));assert.equal(f.city.stock.ore,0);});
test('siege requires war and expiry of protection; destruction loot cannot repeat',()=>{const f=fixture();f.p.realm.houseId='b';const action={houseId:'a',operation:'siege'};assert.throws(()=>settlementAction(f.world,f.p,action,now));f.world.wars.push({attacker:'a',defender:'b',status:'active',endsAt:now+1000000});f.city.protectedUntil=0;f.city.hp=25;f.city.stock.ore=20;settlementAction(f.world,f.p,action,now);assert.equal(f.city.hp,0);assert.equal(f.p.realm.materials.ore,106);assert.equal(f.city.stock.ore,14);assert.throws(()=>settlementAction(f.world,f.p,action,now+3000));assert.equal(f.p.realm.materials.ore,106);});
test('alliance requires reciprocal acceptance and trade conserves stocks',()=>{const f=fixture();f.world.houses.push({id:'b',name:'Casa B',leader:'q'});ensureFrontier(f.world,f.w,f.regions,now);const other=f.world.houses[1],q={realm:{publicId:'q',houseId:'b',materials:{timber:10,ore:0,essence:0},roaming:{x:f.city.x,y:f.city.y}}};settlementAction(f.world,q,{houseId:'a',operation:'alliance'},now);assert.deepEqual(other.allies,[]);Object.assign(f.p.realm.roaming,{x:other.settlement.x,y:other.settlement.y});settlementAction(f.world,f.p,{houseId:'b',operation:'alliance'},now);assert.ok(other.allies.includes('a'));f.city.stock.ore=5;settlementAction(f.world,q,{houseId:'a',operation:'trade',resource:'ore'},now);assert.equal(q.realm.materials.ore,5);assert.equal(q.realm.materials.timber,5);assert.equal(f.city.stock.ore,0);assert.equal(f.city.stock.timber,5);});
