export const CHAPTERS=[
 {id:'ashes',title:'O sino sob as cinzas',speaker:'Iria · Guardiã do Porto',portrait:'oracle',text:'O sino não tocava havia trezentos anos. Agora, cada badalada leva um nome. Antes de escolher uma guerra, aprenda os caminhos de quem ainda vive.',objective:'Descubra 3 regiões e realize 2 coletas.',visits:3,gathers:2,reward:{coins:40,ore:3},choices:[['shelter','Proteger os viajantes','O porto se lembrará de sua compaixão.'],['secrets','Investigar o sino','Há respostas que custam mais que sangue.']]},
 {id:'first-blood',title:'O preço do caminho',speaker:'Kael · Voz do Eclipse',portrait:'kael',text:'Não é a fome que faz de nós monstros. É o que escolhemos quando a fome chega. Enfrente os guardiões e volte com uma resposta.',objective:'Conquiste 2 vitórias em expedições.',wins:2,reward:{coins:50,timber:4,gear:'common'},choices:[['mercy','Poupar os vencidos','Até a floresta pode aprender a confiar.'],['oath','Exigir um juramento','Uma promessa pesa mais que uma corrente.']]},
 {id:'forge',title:'Ferro que se lembra',speaker:'Thorn · Ferreiro dos Juramentos',portrait:'thorn',text:'Toda lâmina guarda o último grito que ouviu. Minha forja pode dar a ela uma nova voz. Traga ferro, madeira e uma razão para continuar.',objective:'Construa a Forja e descubra 5 regiões.',forge:1,visits:5,reward:{coins:60,essence:4,scrap:12},choices:[['restore','Restaurar as relíquias','O que foi quebrado ainda pode proteger.'],['arm','Armar os sentinelas','Que ninguém mais atravesse a noite indefeso.']]},
 {id:'rose',title:'A cadeira vazia',speaker:'Vesper · Regente Carmesim',portrait:'vesper',text:'Todos desejam o trono. Poucos perguntam quem o deixou vazio. Leve sua bandeira até a Coroa e escute o que os cortesãos não ousam dizer.',objective:'Visite a Coroa de Espinhos e conquiste 5 vitórias.',node:'crown',wins:5,reward:{coins:75,essence:6,gear:'uncommon'},choices:[['truth','Revelar a conspiração','A verdade é uma lâmina sem bainha.'],['pact','Firmar um pacto secreto','Nem toda paz pode ser anunciada.']]},
 {id:'sepulchre',title:'O quarto toque',speaker:'Mordrath · Rei Sepultado',portrait:'mordrath',text:'Chamam de maldição aquilo que esqueceram como curar. Desça até meu trono. Quando ouvir a última badalada, decida quem merece despertar.',objective:'Conclua uma dungeon de múltiplas mesas.',dungeons:1,reward:{coins:100,dust:40,gear:'rare'},choices:[['seal','Renovar o selo','Você escolheu o silêncio para proteger os vivos.'],['remember','Guardar a memória do rei','Você levará o nome dos esquecidos.']]},
 {id:'observatory',title:'As estrelas feridas',speaker:'Iria · Orácula do Véu',portrait:'oracle',text:'Há uma noite além desta noite. No observatório, um mapa celeste sangra toda vez que alguém quebra um juramento. Leia-o antes que as estrelas se apaguem.',objective:'Visite o Observatório e construa a Biblioteca.',node:'observatory',library:1,reward:{coins:90,dust:50,essence:8},choices:[['study','Decifrar os presságios','O futuro responde a quem aprende a perguntar.'],['share','Partilhar o conhecimento','Uma vela acende outra sem perder sua luz.']]},
 {id:'abyss',title:'A fome sem rosto',speaker:'Corvo · Vigia da Fronteira',portrait:'raven',text:'Os caçadores desapareceram na Abadia. Seus ecos voltaram, mas suas vozes não. Traga de volta aquilo que a escuridão tentou fazer esquecer.',objective:'Conclua 3 dungeons e descubra 10 regiões.',dungeons:3,visits:10,reward:{coins:120,scrap:30,gear:'rare'},choices:[['rescue','Salvar os prisioneiros','Seu nome será uma história contada ao amanhecer.'],['hunt','Caçar a origem da fome','A noite também aprende a ter medo.']]},
 {id:'eclipse',title:'Um reino para os vivos',speaker:'Vesper & Kael · O Último Conselho',portrait:'vesper',text:'A Coroa não pode pertencer apenas ao sangue ou à lua. Você percorreu as ruínas, ouviu os mortos e escolheu continuar. Que promessa fará a Véspera?',objective:'Visite a Cidadela, alcance nível 5 e conquiste 12 vitórias.',node:'citadel',level:5,wins:12,reward:{coins:180,dust:80,gear:'epic'},choices:[['union','Firmar a concordata','Duas linhagens. Um reino que se recusa a morrer.'],['freedom','Devolver o reino aos viajantes','Nenhum trono vale mais que a liberdade de partir.']]}
];
export const TALENTS={scout:{name:'Batedor da Névoa',icon:'◈',text:'+1 recurso por coleta a cada grau.'},warden:{name:'Guardião das Rotas',icon:'♜',text:'+2 provisões por reabastecimento a cada grau.'},artisan:{name:'Artífice do Sangue',icon:'⚒',text:'+2 sucatas por refino a cada grau.'}};
export function ensureAdventure(r){if(r.adventure)return false;r.adventure={chapter:0,choices:{},claimed:[],journal:[],stats:{gathers:0,wins:0,dungeons:0},talents:{scout:0,warden:0,artisan:0},daily:{day:'',gathers:0,wins:0,claimed:false},reliefAt:0};return true;}
export function dailyState(r,now=Date.now()){ensureAdventure(r);const day=new Date(now).toISOString().slice(0,10);if(r.adventure.daily.day!==day)r.adventure.daily={day,gathers:0,wins:0,claimed:false};return r.adventure.daily;}
export function chapterProgress(r){const a=r.adventure,c=CHAPTERS[a?.chapter||0];if(!c)return {complete:true,ready:false,checks:[]};const checks=[];if(c.visits)checks.push({label:'Regiões descobertas',value:r.visited.length,goal:c.visits});if(c.gathers)checks.push({label:'Coletas',value:a.stats.gathers,goal:c.gathers});if(c.wins)checks.push({label:'Vitórias em expedições',value:a.stats.wins,goal:c.wins});if(c.dungeons)checks.push({label:'Dungeons concluídas',value:a.stats.dungeons,goal:c.dungeons});if(c.node)checks.push({label:'Destino da crônica descoberto',value:r.visited.includes(c.node)?1:0,goal:1});if(c.forge)checks.push({label:'Forja',value:r.holdings.forge,goal:c.forge});if(c.library)checks.push({label:'Biblioteca',value:r.holdings.library,goal:c.library});if(c.level)checks.push({label:'Nível de exploração',value:r.level,goal:c.level});return {chapter:c,checks,ready:checks.every(x=>x.value>=x.goal),complete:false};}
export function talentPoints(r){return Math.max(0,Math.min(9,r.level-1)-Object.values(r.adventure?.talents||{}).reduce((n,x)=>n+x,0));}
export function adventureJournal(r,text,now){r.adventure.journal.unshift({text,at:now});r.adventure.journal=r.adventure.journal.slice(0,30);}
