export const CHAPTERS=[
 {id:'ashes',title:'O sino sob as cinzas',speaker:'Iria · Guardiã do Porto',portrait:'oracle',text:'O sino não tocava havia trezentos anos. Agora, cada badalada leva um nome. Antes de escolher uma guerra, aprenda os caminhos de quem ainda vive.',objective:'Descubra 3 regiões e realize 2 coletas.',visits:3,gathers:2,reward:{coins:40,ore:3},choices:[['shelter','Proteger os viajantes','O porto se lembrará de sua compaixão.'],['secrets','Investigar o sino','Há respostas que custam mais que sangue.']]},
 {id:'first-blood',title:'O preço do caminho',speaker:'Kael · Voz do Eclipse',portrait:'kael',text:'Não é a fome que faz de nós monstros. É o que escolhemos quando a fome chega. Enfrente os guardiões e volte com uma resposta.',objective:'Conquiste 2 vitórias em expedições.',wins:2,reward:{coins:50,timber:4,gear:'common'},choices:[['mercy','Poupar os vencidos','Até a floresta pode aprender a confiar.'],['oath','Exigir um juramento','Uma promessa pesa mais que uma corrente.']]},
 {id:'forge',title:'Ferro que se lembra',speaker:'Thorn · Ferreiro dos Juramentos',portrait:'thorn',text:'Toda lâmina guarda o último grito que ouviu. Minha forja pode dar a ela uma nova voz. Traga ferro, madeira e uma razão para continuar.',objective:'Construa a Forja e descubra 5 regiões.',forge:1,visits:5,reward:{coins:60,essence:4,scrap:12},choices:[['restore','Restaurar as relíquias','O que foi quebrado ainda pode proteger.'],['arm','Armar os sentinelas','Que ninguém mais atravesse a noite indefeso.']]},
 {id:'rose',title:'A cadeira vazia',speaker:'Vesper · Regente Carmesim',portrait:'vesper',text:'Todos desejam o trono. Poucos perguntam quem o deixou vazio. Leve sua bandeira até a Coroa e escute o que os cortesãos não ousam dizer.',objective:'Visite a Coroa de Espinhos e conquiste 5 vitórias.',node:'crown',wins:5,reward:{coins:75,essence:6,gear:'uncommon'},choices:[['truth','Revelar a conspiração','A verdade é uma lâmina sem bainha.'],['pact','Firmar um pacto secreto','Nem toda paz pode ser anunciada.']]},
 {id:'sepulchre',title:'O quarto toque',speaker:'Mordrath · Rei Sepultado',portrait:'mordrath',text:'Chamam de maldição aquilo que esqueceram como curar. Desça até meu trono. Quando ouvir a última badalada, decida quem merece despertar.',objective:'Conclua uma dungeon de múltiplas mesas.',dungeons:1,reward:{coins:100,dust:40,gear:'rare'},choices:[['seal','Renovar o selo','Você escolheu o silêncio para proteger os vivos.'],['remember','Guardar a memória do rei','Você levará o nome dos esquecidos.']]},
 {id:'observatory',title:'As estrelas feridas',speaker:'Iria · Orácula do Véu',portrait:'oracle',text:'Há uma noite além desta noite. No observatório, um mapa celeste sangra toda vez que alguém quebra um juramento. Leia-o antes que as estrelas se apaguem.',objective:'Visite o Observatório e construa a Biblioteca.',node:'observatory',library:1,reward:{coins:90,dust:50,essence:8},choices:[['study','Decifrar os presságios','O futuro responde a quem aprende a perguntar.'],['share','Partilhar o conhecimento','Uma vela acende outra sem perder sua luz.']]},
 {id:'abyss',title:'A fome sem rosto',speaker:'Corvo · Vigia da Fronteira',portrait:'raven',text:'Os caçadores desapareceram na Abadia. Seus ecos voltaram, mas suas vozes não. Traga de volta aquilo que a escuridão tentou fazer esquecer.',objective:'Conclua 3 dungeons e descubra 10 regiões.',dungeons:3,visits:10,reward:{coins:120,scrap:30,gear:'rare'},choices:[['rescue','Salvar os prisioneiros','Seu nome será uma história contada ao amanhecer.'],['hunt','Caçar a origem da fome','A noite também aprende a ter medo.']]},
 {id:'eclipse',title:'Um reino para os vivos',speaker:'Vesper & Kael · O Último Conselho',portrait:'vesper',text:'A Coroa não pode pertencer apenas ao sangue ou à lua. Você percorreu as ruínas, ouviu os mortos e escolheu continuar. Que promessa fará a Véspera?',objective:'Visite a Cidadela, alcance nível 5 e conquiste 12 vitórias.',node:'citadel',level:5,wins:12,reward:{coins:180,dust:80,gear:'epic'},choices:[['union','Firmar a concordata','Duas linhagens. Um reino que se recusa a morrer.'],['freedom','Devolver o reino aos viajantes','Nenhum trono vale mais que a liberdade de partir.']]}
];
CHAPTERS.push(
 {id:'council',title:'O conselho dos sobreviventes',speaker:'Vesper · Regente Carmesim',portrait:'vesper',text:'A guerra terminou nos mapas. Nas ruas, ela ainda cobra dívidas. Conquiste a confiança dos que ficaram: nenhum decreto sustenta um reino sem pão, abrigo e uma voz na Corte.',objective:'Vença 4 expedições conquistando a Corte e alcance nível 6 de exploração.',front:'court',frontWins:4,level:6,reward:{coins:140,essence:10,gear:'rare'},choices:[['council','Convocar o conselho livre','As ruas conquistam voz no conselho.'],['regency','Assumir a regência','Você responde por cada decisão do trono.']]},
 {id:'supply-lines',title:'O inverno das caravanas',speaker:'Thorn · Ferreiro dos Juramentos',portrait:'thorn',text:'Toda espada precisa de ferro, toda sentinela de descanso. O inverno fechou as rotas. Recuperemos as reservas antes que nossos próprios aliados se tornem saqueadores.',objective:'Vença 4 expedições conquistando Catacumbas e eleve a Forja ao nível 2.',front:'crypt',frontWins:4,forge:2,reward:{coins:140,ore:12,timber:8,scrap:25},choices:[['caravans','Escoltar as caravanas','O pão chega antes das bandeiras.'],['stores','Reabrir os armazéns','As reservas pertencem aos que resistiram.']]},
 {id:'last-hunt',title:'O uivo além da fronteira',speaker:'Kael · Voz do Eclipse',portrait:'kael',text:'Não marcharemos por vingança. Marcharemos para que ninguém precise fugir de novo. Reúna os veteranos e leve a Caçada até a última passagem do Abismo.',objective:'Vença 4 expedições conquistando a Caçada e conclua 5 dungeons.',front:'hunt',frontWins:4,dungeons:5,reward:{coins:180,scrap:35,gear:'epic'},choices:[['watch','Fundar a Vigília','A fronteira recebe guardiões, não conquistadores.'],['pursuit','Perseguir o último eco','Você corta o caminho da fome.']]},
 {id:'legacy',title:'O nome que atravessa a noite',speaker:'Iria · Guardiã do Porto',portrait:'oracle',text:'Coroas caem. Os gestos permanecem. Há um lugar à mesa para aqueles que governaram, cuidaram e lutaram. Conte aos viajantes por que Véspera ainda existe.',objective:'Alcance nível 8, descubra 15 regiões e conquiste 30 vitórias.',level:8,visits:15,wins:30,reward:{coins:240,dust:100,gear:'epic'},choices:[['chronicle','Escrever a crônica','Sua jornada torna-se o primeiro mapa dos que virão.'],['departure','Partir ao amanhecer','Há outras noites esperando um juramento.']]}
);
CHAPTERS.push(
 {id:'lanterns',title:'As lanternas do regresso',speaker:'Iria · Guardiã do Porto',portrait:'oracle',text:'A crônica chegou ao porto antes de você. Agora os refugiados pedem caminhos seguros, não novas coroas. Acenda lanternas onde antes deixávamos os viajantes sozinhos.',objective:'Realize 80 coletas e eleve o Acampamento ao nível 3.',gathers:80,camp:3,reward:{coins:160,timber:15,scrap:20},choices:[['shelters','Erguer abrigos nas rotas','Cada lanterna recebe o nome de um viajante.'],['guides','Formar uma ordem de guias','Quem conhece a estrada jamais viaja sozinho.']]},
 {id:'broken-seals',title:'O arquivo dos selos partidos',speaker:'Corvo · Vigia da Fronteira',portrait:'raven',text:'O primeiro selo não foi quebrado por fome. Alguém o abriu por dentro. Os fragmentos espalhados nos sepulcros carregam a mesma assinatura. Reúna os testemunhos antes que desapareçam.',objective:'Conclua 10 dungeons e eleve a Biblioteca ao nível 3.',dungeons:10,library:3,reward:{coins:190,dust:80,essence:15},choices:[['testimony','Publicar os testemunhos','Véspera aprende o nome de seus traidores.'],['witnesses','Proteger as testemunhas','As vozes sobrevivem para contar sua própria história.']]},
 {id:'new-dawn',title:'Um lugar à mesa',speaker:'Thorn · Ferreiro dos Juramentos',portrait:'thorn',text:'Você trouxe de volta ferro, nomes e histórias. Falta decidir o que construir com eles. Deixe a espada descansar por uma noite. Amanhã, haverá outras fronteiras; hoje, há lugar para todos.',objective:'Alcance nível 12 e conquiste 50 vitórias em expedições.',level:12,wins:50,reward:{coins:220,scrap:40,gear:'epic'},choices:[['school','Fundar a Escola da Vigília','O que você aprendeu agora protege quem está começando.'],['sanctuary','Construir o Santuário dos Juramentos','Duas linhagens encontram abrigo sob o mesmo teto.']]}
);
export const TALENTS={scout:{name:'Batedor da Névoa',icon:'◈',text:'+1 recurso por coleta a cada grau.'},warden:{name:'Guardião das Rotas',icon:'♜',text:'+2 provisões por reabastecimento a cada grau.'},artisan:{name:'Artífice do Sangue',icon:'⚒',text:'+2 sucatas por refino a cada grau.'}};
export function ensureAdventure(r){if(r.adventure){if(!r.adventure.stats.fronts){r.adventure.stats.fronts={court:0,crypt:0,hunt:0};return true;}return false;}r.adventure={chapter:0,choices:{},claimed:[],journal:[],stats:{gathers:0,wins:0,dungeons:0,fronts:{court:0,crypt:0,hunt:0}},talents:{scout:0,warden:0,artisan:0},daily:{day:'',gathers:0,wins:0,claimed:false},reliefAt:0};return true;}
export function dailyState(r,now=Date.now()){ensureAdventure(r);const day=new Date(now).toISOString().slice(0,10);if(r.adventure.daily.day!==day)r.adventure.daily={day,gathers:0,wins:0,claimed:false};return r.adventure.daily;}
export function chapterProgress(r){const a=r.adventure,c=CHAPTERS[a?.chapter||0];if(!c)return {complete:true,ready:false,checks:[]};const checks=[];if(c.front)checks.push({label:'Expedições vencidas com '+({court:'Corte',crypt:'Catacumbas',hunt:'Caçada'}[c.front]),value:a.stats.fronts?.[c.front]||0,goal:c.frontWins});if(c.visits)checks.push({label:'Regiões descobertas',value:r.visited.length,goal:c.visits});if(c.gathers)checks.push({label:'Coletas',value:a.stats.gathers,goal:c.gathers});if(c.wins)checks.push({label:'Vitórias em expedições',value:a.stats.wins,goal:c.wins});if(c.dungeons)checks.push({label:'Dungeons concluídas',value:a.stats.dungeons,goal:c.dungeons});if(c.node)checks.push({label:'Destino da crônica descoberto',value:r.visited.includes(c.node)?1:0,goal:1});if(c.camp)checks.push({label:'Acampamento',value:r.holdings.camp,goal:c.camp});if(c.forge)checks.push({label:'Forja',value:r.holdings.forge,goal:c.forge});if(c.library)checks.push({label:'Biblioteca',value:r.holdings.library,goal:c.library});if(c.level)checks.push({label:'Nível de exploração',value:r.level,goal:c.level});return {chapter:c,checks,ready:checks.every(x=>x.value>=x.goal),complete:false};}
export function talentPoints(r){return Math.max(0,Math.min(9,r.level-1)-Object.values(r.adventure?.talents||{}).reduce((n,x)=>n+x,0));}
export function adventureJournal(r,text,now){r.adventure.journal.unshift({text,at:now});r.adventure.journal=r.adventure.journal.slice(0,30);}
