// New accounts enter a gradual journey. Absence of version preserves veteran access.
export const FEATURES={
 collection:{name:'Arsenal',at:0,icon:'◈'},loadout:{name:'Preparação',at:0,icon:'⚒'},
 decks:{name:'Construção de decks',at:1,icon:'♜'},boosters:{name:'Boosters',at:1,icon:'✦'},contracts:{name:'Contratos',at:1,icon:'⚔'},
 forge:{name:'Forja',at:2,icon:'⚒'},dungeon:{name:'Dungeon do Rei Sepultado',at:2,icon:'♛'},lineage:{name:'Segunda linhagem',at:12,icon:'☾'},
 realms:{name:'Reinos de Véspera',at:3,icon:'⌖'},vault:{name:'Cofre',at:3,icon:'◈'},
 market:{name:'Comércio e encomendas',at:4,icon:'⚖'},duel:{name:'Matchmaking online',at:5,icon:'⚔'},politics:{name:'Casas e política',at:6,icon:'♜'}
};
export function isJourneyAccount(profile){return profile?.journey?.version===1;}
export function featureOpen(profile,key){return (key==='lineage'&&!!profile?.dualStartersGranted)||!FEATURES[key]||!isJourneyAccount(profile)||(profile.matches||0)>=FEATURES[key].at;}
export function featureRequirement(profile,key){const f=FEATURES[key];return f?`${f.name}: conclua ${f.at} ${f.at===1?'batalha':'batalhas'} (${Math.min(profile.matches||0,f.at)}/${f.at}). Vitórias e derrotas contam; desistências não.`:'';}
export function assertFeature(profile,key){if(!featureOpen(profile,key))throw new Error(featureRequirement(profile,key));}
export function journeyAct(profile){
 const chapter=profile.realm?.adventure?.chapter||0,matches=profile.matches||0;
 if(chapter>=8)return {id:3,title:'IV · Legado da noite',goal:'A Crônica principal terminou. Aperfeiçoe seus decks, conclua histórias, conquiste troféus e dispute Reinos ou a arena.'};
 if(matches>=6)return {id:2,title:'III · Soberania',goal:'Avance até o fim da Crônica, derrote os chefes e escolha seu papel nas Casas de Véspera.'};
 if(matches>=2)return {id:1,title:'II · Além dos portões',goal:'Prepare relíquias, enfrente a dungeon e abra caminho para explorar os Reinos.'};
 return {id:0,title:'I · O primeiro juramento',goal:'Aprenda na mesa de treino e conclua sua primeira caçada com o deck inicial.'};
}
// Every screen teaches its own next decisions; the combat academy remains hands-on.
export const JOURNEY_LESSONS={
 camp:{name:'Erguer seu domínio',steps:[['Seu refúgio cresce','Escolha uma construção no cenário. O painel lateral mostra seu nível, o benefício e o custo exato da próxima melhoria.','.rs-building-detail'],['Preparar a próxima rota','Aumente as provisões no acampamento e confira seus recursos no alto antes de partir.','[data-rs-building="camp"]']]},
 chronicle:{name:'Crônica, talentos e histórias',steps:[['Um capítulo por vez','Cada capítulo apresenta objetivos concretos. Cumpra-os e escolha um desfecho para receber a recompensa e abrir o seguinte.','.adventure-dialogue'],['Evolução de explorador','Ganhe experiência nos Reinos e invista os pontos disponíveis em talentos. Leia cada benefício antes de confirmar.','[data-rs-page="talents"]'],['Além da história principal','Histórias paralelas e objetivos recorrentes abrem novas metas; o fim da Crônica não encerra seu personagem.','[data-rs-page="stories"]']]},
 welcome:{name:'Seu primeiro juramento',steps:[['O começo da noite','Você recebeu um deck pronto e recursos iniciais. Comece pelo treino seguro; as outras atividades serão apresentadas aos poucos.','[data-academy-start]'],['Aprenda na mesa','O treino ensina invocação, equipamento, ataque, habilidade, as três frentes e a suprema. Você pode sair e repetir sem desgaste.','[data-academy-start]'],['Sua primeira caçada','Depois, enfrente a IA. Concluir a batalha libera decks, boosters e contratos, mesmo se você perder. Desistir não conta.','[data-start="practice"]']]},
 collection:{name:'Ler sua coleção',steps:[['Reconheça a carta','Custo no alto; ataque e vida embaixo. Os selos explicam os efeitos na prévia, sem esconder a ilustração.','.collection-grid'],['Inspecione sem decorar','No PC, passe o mouse. No celular, toque para inspecionar. As descrições de cada selo ficam ao lado da carta.','.collection-grid .game-card'],['Cartas e peças','Aliados e magias ficam na coleção. Equipamentos representam peças físicas com durabilidade, disponíveis no Relicário.','.collection-wallet']]},
 decks:{name:'Seu estilo de combate',steps:[['Escolha uma lista','Editar muda a composição. Ativar escolhe a lista usada na próxima partida.','.deck-list'],['Uma lista saudável','20 cartas, pelo menos 8 aliados e 2 aliados baratos; até 6 equipamentos. A validação mostra o que falta.','.deck-stats'],['Salve e prepare','Salvar não compra peças. Confira a preparação para resolver relíquias indisponíveis antes de jogar.','[data-modal="loadout"]']]},
 loadout:{name:'Armar a expedição',steps:[['Leia a prontidão','20 cartas não significam 20 peças livres. A preparação confere itens, durabilidade e reservas.','.forge-status'],['Reservas mantêm você jogando','Peças esgotadas saem da lista e recebem substitutos válidos. A sugestão usa somente seu inventário.','.forge-plan'],['Sua decisão final','Escolha outras relíquias ou aplique a sugestão. O botão também ativa o deck, sem gastar moedas automaticamente.','[data-loadout-auto]']]},
 boosters:{name:'Novas possibilidades',steps:[['Confira o custo','Boosters gastam Marcas da bolsa. São uma opção para ampliar estilos; não são exigidos para continuar jogando.','[data-buy-booster]'],['Revele e inspecione','Cada carta revelada pode ser inspecionada. Equipamentos recebidos viram peças persistentes.','.booster-results-slot'],['Leve ao deck','Novas cartas vão à coleção. Edite e ative seu deck para usá-las; abrir um pacote não altera sua lista.','[data-modal="decks"]']]},
 contracts:{name:'Objetivos e recompensas',steps:[['Jogue com um objetivo','Contratos acompanham caçadas, vitórias e abates. Veja a recompensa antes de escolher o próximo destino.','.contract-board'],['Recompensa automática','Ao cumprir o marco, o servidor concede o prêmio. Não precisa procurar um botão escondido para recebê-lo.','.contract-track']]},
 inventory:{name:'Cuidar das relíquias',steps:[['Uma peça, um estado','Utilizável, esgotada, anunciada ou reservada: o estado explica se a peça pode entrar no deck.','.trade-grid'],['Reparar ou substituir','Selecione a peça e confira o custo de reparo. Se não quiser gastar, volte à preparação e use reservas.','.trade-item-detail'],['Proteção do juramento','Peças vinculadas não podem ser comercializadas. Itens negociáveis seguem as regras de risco do modo de combate.','.trade-item-actions']]},
 forge:{name:'Forjar seu equipamento',steps:[['Uma receita concreta','Escolha a relíquia. A receita mostra Marcas e Sucata necessárias, antes da confirmação.','.forge-recipe'],['Criar não equipa','A peça nova vai ao inventário. Abra Preparar para escolher seu lugar no deck.','[data-modal="loadout"]']]},
 vault:{name:'Seu tesouro',steps:[['Bolsa e cofre','Compras usam a bolsa. Guardar e retirar transferem o mesmo valor, sem taxas ou juros.','.vault-transfer-balances'],['As Marcas tomam forma','As moedas caem, colidem e podem ser arrastadas. A quantidade é ilustrativa; o número mostra seu saldo exato.','[data-vault-physics]'],['Reserve Marcas para a próxima viagem','Retire o necessário para reparos, forja e compras. Mover moedas com o dedo não movimenta dinheiro.','#vault-amount']]},
 market:{name:'Comércio entre jogadores',steps:[['Compra de uma peça real','Cada oferta possui preço e vendedor. A peça anunciada deixa de estar disponível ao vendedor para jogar.','.trade-grid'],['Preços e impostos','Confira o preço final e a durabilidade. A venda tem imposto; anunciar também tem taxa.','.trade-item-detail']]},
 orders:{name:'Encomendar e fornecer',steps:[['Pagamento reservado','Uma encomenda retira as Marcas da bolsa imediatamente. Cancelar devolve a reserva. Até três pedidos por jogador.','.trade-grid'],['Entrega segura','Só uma peça livre, negociável e totalmente reparada pode atender o pedido. O fornecedor recebe o valor líquido do imposto.','.trade-item-detail'],['Criar um pedido','Na Forja, selecione a relíquia e abra Encomendar de um jogador para definir sua oferta.','[data-trade-zone="forge"]']]},
 realms:{name:'Primeiros passos em Véspera',steps:[['Uma mesa viva','Arraste o mapa, aproxime ou expanda. Selecione uma região e viaje por rotas conectadas. Os retratos mostram viajantes presentes.','.world-table-viewport'],['Destaque seus aliados','Selecione uma carta e um espaço local. Corte prepara influência; Catacumbas produzem recursos; Caçada marca presença defensiva. Cada posto custa Marcas e materiais.','.world-command'],['Uma campanha com destino','Siga a Crônica, aceite histórias e enfrente instâncias. O nível de exploração é separado do nível da conta e do nível da mesa.','.realm-map']]},
 politics:{name:'Uma Casa na noite',steps:[['Influência além da mesa','Casas, doações e propostas afetam o mundo persistente. Leia o custo e o efeito antes de confirmar.','.realm-map'],['Guerra é uma escolha','Avance a Crônica e fortaleça sua economia antes de investir em disputas. O progresso solo continua disponível.','.realm-map']]},
 dungeon:{name:'O Rei Sepultado',steps:[['Uma prova maior','A dungeon coloca seu deck contra um chefe com regras próprias. Prepare equipamento e leia a descrição do encontro.','[data-start="dungeon"]'],['Persistência e recuperação','Depois da luta, confira o saque e o desgaste. Uma derrota não exige comprar outro deck; use a preparação.','[data-modal="loadout"]']]},
 duel:{name:'Arena online',steps:[['Busca automática','O matchmaking procura um adversário. Não é necessário trocar códigos. Você pode cancelar a busca enquanto espera.','[data-match-search]'],['Leia o pacto de risco','Confira o modo e as regras de perda de equipamento antes de confirmar. A progressão solo permanece disponível.','#duel-risk']]},
 legacy:{name:'Seu legado',steps:[['Começo, travessia e conclusão','Conclua os capítulos da Crônica e derrote o Rei Sepultado. Depois, continue por histórias, troféus, decks e disputas.','.legacy-profile'],['Escolha seu próximo objetivo','Não há obrigação de entrar no PvP. Campanha, exploração e construção de coleção têm seus próprios objetivos.','.trophy']]}
};
export function lessonFeature(id){return ({welcome:null,inventory:null,camp:'realms',chronicle:'realms',orders:'market',legacy:null})[id]??(FEATURES[id]?id:null);}
