import {buildClassAbilities,CLASS_SKILLS,REALM_CLASSES,ensureSkillTree,knowsClassSkill,treeBonus,skillTreeView,skillTreeChoice} from './realm-skill-trees.js';
import {equippedItem} from './realm-equipment.js';
import {CARDS} from './cards.js';
import {RuleError} from './engine.js';
import {ensureLifeSkills,lifeSkillView,lifeTalentChoice,skillLevel} from './realm-life-skills.js';

export const ATTRIBUTES={strength:'Força',dexterity:'Destreza',constitution:'Vigor',intelligence:'Intelecto',wisdom:'Percepção',charisma:'Presença'};
export const PATHS={sentinel:{name:'Sentinela',attribute:'strength',text:'Aço e resistência: +2 Força, guarda reforçada.'},stalker:{name:'Predador',attribute:'dexterity',text:'Precisão e mobilidade: +2 Destreza, críticos ferem mais.'},arcanist:{name:'Teurgista',attribute:'intelligence',text:'Rituais do Véu: +2 Intelecto, +20 mana.'}};
export const ABILITIES={
 strike:{id:'strike',name:'Corte',icon:'⚔',key:'Espaço',level:1,cooldown:650,windup:160,damageType:'physical',energy:0,mana:0,range:4.5,dice:6,attribute:'strength',text:'Corte direcional após 0,16 s. O terceiro acerto seguido ganha +4 dano. Pode ser cancelado com uma defesa.'},
 cleave:{id:'cleave',name:'Arco de aço',icon:'◒',key:'1',level:1,cooldown:4200,windup:330,damageType:'physical',energy:16,mana:0,range:5,dice:10,attribute:'strength',area:3,text:'Golpe em leque após 0,33 s. Atinge até cinco inimigos à frente; obstáculos bloqueiam o corte.'},
 bolt:{id:'bolt',name:'Lança do Véu',icon:'✦',key:'2',level:1,cooldown:1700,windup:230,speed:13,damageType:'magic',energy:0,mana:9,range:11,dice:10,attribute:'intelligence',text:'Projétil arcano com trajetória real. Colide com o primeiro inimigo ou obstáculo no caminho.'},
 dash:{id:'dash',name:'Passo espectral',icon:'➶',key:'Shift',level:1,cooldown:3200,energy:12,mana:0,range:3.8,text:'Cancela sua preparação e esquiva por 500 ms. Corpos e estruturas bloqueiam o deslocamento.'},
 guard:{id:'guard',name:'Guarda de ferro',icon:'⬡',key:'3',level:1,cooldown:8000,energy:10,mana:0,range:0,text:'Barreira frontal por 3 s. Absorve dano físico e mágico até quebrar; suas costas continuam expostas.'},
 parry:{id:'parry',name:'Contraguarda',icon:'⚔',key:'Q',level:1,cooldown:4400,energy:14,mana:0,range:0,text:'Counter físico frontal por 0,65 s. Apara o golpe, cancela a preparação inimiga e atordoa por 1,2 s.'},
 reflect:{id:'reflect',name:'Espelho do Véu',icon:'◈',key:'E',level:1,cooldown:6200,energy:0,mana:14,range:0,text:'Counter mágico frontal por 0,8 s. Devolve o primeiro projétil ao lançador e cancela sua preparação.'},
 mend:{id:'mend',name:'Sangue renovado',icon:'♥',key:'4',level:2,cooldown:10000,energy:0,mana:18,range:0,text:'Recupera 2d8 + Percepção + nível de vida.'},
 frost:{id:'frost',name:'Círculo lunar',icon:'❄',key:'5',level:3,cooldown:8000,windup:420,speed:11,damageType:'magic',energy:0,mana:22,range:9,dice:8,attribute:'wisdom',area:4,save:true,text:'Orbe que explode ao colidir ou alcançar a mira. Resistência reduz o dano; imobiliza por 2 s. Paredes protegem da explosão.'},
 drain:{id:'drain',name:'Pacto carmesim',icon:'◈',key:'6',level:4,cooldown:6500,windup:280,speed:15,damageType:'magic',energy:0,mana:17,range:8,dice:12,attribute:'charisma',text:'Projétil de sangue: o impacto drena metade do dano causado como vida.'},
 tempest:{id:'tempest',name:'Eclipse',icon:'☽',key:'7',level:6,cooldown:16000,windup:600,speed:9,damageType:'magic',energy:10,mana:35,range:10,dice:12,attribute:'intelligence',area:5,save:true,text:'Orbe do eclipse com explosão de 2d12. Resistência reduz à metade. Colisões antecipam a explosão.'}
};
Object.assign(ABILITIES,buildClassAbilities(ABILITIES));
export const TALENTS={bulwark:{name:'Muralha viva',text:'+2 defesa por grau. Especialização defensiva.',max:3},ferocity:{name:'Fúria da fronteira',text:'+3 dano físico por grau. Especialização ofensiva.',max:3},reservoir:{name:'Reservas arcanas',text:'+15 mana máxima por grau.',max:3},vitality:{name:'Sangue ancestral',text:'+12 vida máxima por grau.',max:3},precision:{name:'Lâmina certeira',text:'+1 nos ataques d20 por grau.',max:3},channel:{name:'Canalização',text:'+8 mana e +1 dano mágico por grau.',max:3},steward:{name:'Regente',text:'+1 produção por grau nas ordens de abastecimento.',max:3}};
export const modifier=value=>Math.floor((value-10)/2);
export const ORIGINS={exile:{name:'Exilado das muralhas',text:'+2 Vigor. Resistência para sobreviver na fronteira.',attribute:'constitution'},hunter:{name:'Caçador da Lua',text:'+2 Destreza. Precisão e defesa móvel.',attribute:'dexterity'},scholar:{name:'Iniciado do Véu',text:'+2 Intelecto. Poder para construir um arsenal mágico.',attribute:'intelligence'},diplomat:{name:'Herdeiro sem trono',text:'+2 Presença. Poder de sangue e influência.',attribute:'charisma'}};
export const SPECIALIZATIONS={juggernaut:{name:'Bastião',text:'+25 vida e +2 defesa.',level:5},executioner:{name:'Carrasco',text:'+6 dano físico.',level:5},oracle:{name:'Oráculo',text:'+25 mana e +2 Intelecto.',level:5}};
const legacyThreshold=level=>100*(level-1)*level;
export function levelThreshold(level){
 if(level<=1)return 0;
 const early=n=>n<=5?100*(n-1)*n:2000;
 if(level<=5)return early(level);
 let xp=early(5);for(let n=6;n<=Math.min(level,12);n++)xp+=1200+(n-6)*450;
 for(let n=13;n<=level;n++)xp+=5600+(n-13)*1700;
 return xp;
}
export function ensureRpg(p){
 if(!p.rpg)p.rpg={schema:2,xp:Math.max(0,Math.floor((p.xp||0)*.2)),path:null,attributes:{strength:12,dexterity:12,constitution:12,intelligence:12,wisdom:12,charisma:12},spent:0,talents:{},cooldowns:{},mana:50,combo:0,comboAt:0,stats:{kills:0,raids:0,arena:0,duels:0,dungeons:0,gathers:0},claims:[],loadout:['cleave','bolt','guard','mend'],log:[]};
 const r=p.rpg;r.presets||={};
 if((r.schema||1)<2){let old=1;while(old<20&&r.xp>=legacyThreshold(old+1))old++;const oldStart=legacyThreshold(old),oldEnd=legacyThreshold(old+1),progress=Math.max(0,Math.min(1,(r.xp-oldStart)/(oldEnd-oldStart)));r.xp=Math.floor(levelThreshold(old)+progress*(levelThreshold(old+1)-levelThreshold(old)));r.schema=2;}
 r.level=1;while(r.level<20&&r.xp>=levelThreshold(r.level+1))r.level++;ensureLifeSkills(p);ensureSkillTree(p);if(!r.treeLoadoutInitialized){r.loadout=[`${r.skillTree.classId}_0`,...(r.loadout||['bolt','guard','mend']).slice(1,4)];r.treeLoadoutInitialized=true;}return r;
}
export function rpgStats(p){const r=ensureRpg(p),a={...r.attributes},lineage=Math.min(8,p.realm?.lineage?.level||0),skills=r.lifeSkills;if(r.path)a[PATHS[r.path].attribute]+=2;if(ORIGINS[r.origin])a[ORIGINS[r.origin].attribute]+=2;if(r.specialization==='oracle')a.intelligence+=2;const equipment=(p.realm?.roaming?.equipment||[]).filter(id=>equippedItem(p,id));const gear=equipment.map(id=>CARDS[id]).filter(Boolean),masteryPower=Math.min(4,equipment.reduce((n,id)=>n+Math.floor((skillLevel(skills.equipment[id]||0)-1)/10),0));return {attributes:a,modifiers:Object.fromEntries(Object.entries(a).map(([k,v])=>[k,modifier(v)])),proficiency:2+Math.floor((r.level-1)/4),defense:treeBonus(p,'defense')+10+(r.specialization==='juggernaut'?2:0)+modifier(a.dexterity)+(r.talents.bulwark||0)*2+(p.campaign?.projects.bastion||0)+Math.min(4,gear.reduce((n,c)=>n+(c.health||0),0)),maxHp:treeBonus(p,'maxHp')+100+(r.specialization==='juggernaut'?25:0)+(r.level-1)*4+Math.max(0,modifier(a.constitution)-1)*5+(r.talents.vitality||0)*12+gear.reduce((n,c)=>n+(c.health||0)*5,0)+lineage*4,maxMana:treeBonus(p,'maxMana')+50+(r.specialization==='oracle'?25:0)+(r.talents.reservoir||0)*15+(r.level-1)*4+(r.path==='arcanist'?20:0)+(r.talents.channel||0)*8,weapon:treeBonus(p,'weapon')+(r.specialization==='executioner'?6:0)+(r.talents.ferocity||0)*3+gear.reduce((n,c)=>n+(c.attack||0)*2,0)+Math.floor(lineage/2)+masteryPower+(skills.talents.edge||0),magicMastery:treeBonus(p,'magicMastery')+(skills.talents.channel||0),guardMastery:treeBonus(p,'guardMastery')+(skills.talents.brace||0)*3,equipment};}
export function gainRpg(p,amount,source,context={}){const r=ensureRpg(p);let earned=Math.max(0,Math.floor(amount));if(context.targetLevel&&['kills','dungeons','raids'].includes(source)){const gap=context.targetLevel-r.level;earned=Math.floor(earned*(gap<=-6?.12:gap<=-3?.35:gap>=5?1.18:1));}r.xp+=earned;if(source&&source in r.stats)r.stats[source]++;ensureRpg(p);return r;}
export function rollD20(bonus,defense,rng=Math.random,advantage=0){const first=1+Math.floor(rng()*20),second=advantage?1+Math.floor(rng()*20):first,natural=advantage>0?Math.max(first,second):advantage<0?Math.min(first,second):first;return {natural,total:natural+bonus,defense,critical:natural===20,hit:natural===20||(natural!==1&&natural+bonus>=defense),rolls:advantage?[first,second]:[first]};}
export function rollDice(count,sides,rng=Math.random){let n=0;for(let i=0;i<count;i++)n+=1+Math.floor(rng()*sides);return n;}
export function rpgView(p,now){const r=ensureRpg(p),stats=rpgStats(p);const {usedAt,...lifeSkills}=lifeSkillView(p);return {...structuredClone(r),...stats,lifeSkills,skillTree:skillTreeView(p),faction:p.starterFaction,nextXP:levelThreshold(r.level+1),startXP:levelThreshold(r.level),points:Math.max(0,(r.level-1)*2-r.spent),talentPoints:Math.max(0,Math.floor(r.level/2)-Object.values(r.talents).reduce((a,b)=>a+b,0)),abilities:Object.values(ABILITIES).filter(a=>!a.classId||a.classId===r.skillTree.classId).map(a=>({...a,unlocked:a.classId?knowsClassSkill(p,a.id):r.level>=a.level,remaining:Math.max(0,(r.cooldowns[a.id]||0)-now)})),origins:ORIGINS,specializations:SPECIALIZATIONS,paths:PATHS,talentDefinitions:TALENTS,attributeNames:ATTRIBUTES};}
export function rpgChoice(p,input,now=Date.now()){const r=ensureRpg(p);const check=(v,m)=>{if(!v)throw new RuleError(m);};
 if(['rpg-tree-learn','rpg-tree-reset','rpg-class-change'].includes(input.type))return skillTreeChoice(p,input,now);
 if(input.type==='rpg-life-talent')return lifeTalentChoice(p,input.talent);
 if(input.type==='rpg-origin'){check(!r.origin&&Object.hasOwn(ORIGINS,input.origin),'Escolha uma origem disponível.');r.origin=input.origin;}
 else if(input.type==='rpg-specialization'){check(!r.specialization&&Object.hasOwn(SPECIALIZATIONS,input.specialization)&&r.level>=5,'Especialização disponível a partir do nível 5.');r.specialization=input.specialization;}
 else if(input.type==='rpg-preset-save'){check([1,2,3].includes(input.slot),'Escolha um dos três perfis.');r.presets[input.slot]={classId:r.skillTree.classId,loadout:[...r.loadout],attributes:{...r.attributes},talents:{...r.talents},spent:r.spent};}
 else if(input.type==='rpg-preset-load'){const preset=r.presets[input.slot];check(preset,'Perfil não salvo.');check(preset.classId===r.skillTree.classId&&preset.loadout.every(id=>!CLASS_SKILLS[id]||knowsClassSkill(p,id)),'Este perfil usa habilidades que não estão aprendidas nesta classe.');check(now-(p.realm?.roaming?.lastCombatAt||0)>12000,'Troque sua build fora do combate.');r.loadout=[...preset.loadout];r.attributes={...preset.attributes};r.talents={...preset.talents};r.spent=preset.spent;}
 else if(input.type==='rpg-respec'){check((p.coins||0)>=50,'Redistribuição custa 50 Marcas.');check(now-(p.realm?.roaming?.lastCombatAt||0)>12000,'Afaste-se do combate.');p.coins-=50;r.attributes=Object.fromEntries(Object.keys(ATTRIBUTES).map(k=>[k,12]));r.spent=0;r.talents={};}
 else if(input.type==='rpg-path'){check(!r.path&&PATHS[input.path],'Escolha uma vocação disponível; o juramento é permanente.');r.path=input.path;}
 else if(input.type==='rpg-attribute'){check(ATTRIBUTES[input.attribute]&&r.attributes[input.attribute]<20&&r.spent<(r.level-1)*2,'Não há pontos disponíveis para este atributo.');r.attributes[input.attribute]++;r.spent++;}
 else if(input.type==='rpg-talent'){const t=TALENTS[input.talent];check(t&&(r.talents[input.talent]||0)<t.max&&Object.values(r.talents).reduce((a,b)=>a+b,0)<Math.floor(r.level/2),'Talento indisponível ou sem pontos.');r.talents[input.talent]=(r.talents[input.talent]||0)+1;}
 else if(input.type==='rpg-loadout'){const a=ABILITIES[input.ability];check(Number.isInteger(input.slot)&&input.slot>=0&&input.slot<4&&a&&(a.classId?knowsClassSkill(p,a.id):r.level>=a.level)&&!['strike','dash'].includes(a.id),'Habilidade ou posição indisponível.');const previous=r.loadout.indexOf(a.id);if(previous>=0)r.loadout[previous]=r.loadout[input.slot];r.loadout[input.slot]=a.id;}
 else throw new RuleError('Escolha de personagem desconhecida.');return {message:'Ficha de personagem atualizada.'};
}
