import {RuleError} from './engine.js';
const check=(ok,message)=>{if(!ok)throw new RuleError(message);};

export const VESPERA_CHRONICLE=Object.freeze([
 {id:'oath',act:'I · A Vigília',title:'O juramento sob duas luas',hint:'O primeiro passo em Véspera.',voice:'Iria, guardiã do Porto',text:'Véspera nasceu de um acordo, não de uma vitória. Quando a primeira lua se partiu, o céu despejou essência sobre florestas, minas e gente. Vampiros e lobisomens aprenderam a sobreviver à mesma noite por caminhos opostos: os primeiros preservaram a memória no sangue; os segundos, nas trilhas e nas histórias da matilha. A Vigília ergueu o Porto das Cinzas sobre a única passagem que nenhum dos dois podia defender sozinho. Ali a paz não é perdão: é tempo emprestado para escolher quem você será.'},
 {id:'ash',act:'I · A Vigília',title:'As cinzas guardam nomes',hint:'Converse com um emissário ou cronista.',voice:'Toren, juramentado da Lua',text:'Os errantes carregam nomes apagados da guerra antiga. Não são monstros sem passado. Muitos seguiram senhores que prometeram um fim ao ciclo de fome e caça; receberam em troca o Véu, uma névoa que preserva o corpo e cobra a lembrança. A Vigília registra cada criatura abatida porque teme que um dia não reste ninguém capaz de dizer quem ela foi. Os cronistas escondem cópias dessas listas em cada posto. Quem lê entende que a guerra não começou com a diferença entre linhagens, mas com o preço de dominar a morte.'},
 {id:'roots',act:'II · A Fronteira',title:'Raízes de ferro e sangue',hint:'Complete uma coleta de recursos.',voice:'Nessa, mercadora das Cinzas',text:'A madeira das matas toca o minério sob o solo; o minério conduz a essência que corre para os poços do Véu. Por isso um posto prospera apenas quando suas fontes combinam com a terra. A antiga coroa tentou arrancar tudo de uma vez e deixou campos estéreis. A cada fonte exaurida, a natureza procura outra fissura para renascer. Os mercados aprenderam a seguir essas mudanças, e uma cidade sem estrada, caravanas e guardas não passa de um cofre esperando ladrões.'},
 {id:'hunt',act:'II · A Fronteira',title:'A lei da presa',hint:'Derrote sua primeira criatura.',voice:'A matilha da Lua Oca',text:'Caçar em Véspera é reconhecer uma fronteira. A matilha recolhe carne e pele para alimentar o povo; um predador que mata apenas para contar corpos perde o direito de liderar. Vampiros guardam outra lei: o sangue tomado sem propósito deixa uma dívida que volta em forma de fome. As duas tradições discordam de quase tudo, mas sabem que uma presa abatida pertence primeiro a quem assumiu o risco. Aliados que combateram juntos dividem o espólio; o resto do mundo espera a proteção terminar.'},
 {id:'houses',act:'III · Os Domínios',title:'Casas feitas de vontade',hint:'Funde ou visite a cidade de uma Casa.',voice:'Anais das Casas',text:'As Casas surgiram quando capitais distantes deixaram de proteger as estradas. Cada estandarte promete abrigo em troca de trabalho, tributo e lealdade. Uma cidade tem reservas, muralhas, oficinas, política e memória dos ataques que sofreu. Guerras mudam o controle dos postos e a direção das caravanas; alianças podem abrir comércio ou apenas adiar uma invasão. Não há trono permanente em Véspera: a terra reconhece quem consegue mantê-la viva.'},
 {id:'bloodcraft',act:'III · Os Domínios',title:'A arte do domador',hint:'Transforme seu primeiro servo vampiro.',voice:'Livro dos Pactos Carmesins',text:'Os domadores vampiros não erguem cidades sozinhos. Depois de vencer um inimigo humanoide, podem selar um pacto no sangue e convocar um servo para o domínio. O pacto exige essência, reserva de sangue e uma Casa capaz de acolhê-lo. Servos colhem recursos, defendem muralhas ou escoltam o comércio conforme a ordem recebida. Cada serviço prolonga o vínculo, mas nenhum senhor possui mais vontades do que consegue sustentar. É por isso que poder sem logística desmorona tão depressa.'},
 {id:'mooncraft',act:'III · Os Domínios',title:'A mesa da matilha',hint:'Prepare sua primeira presa.',voice:'Cantos da Trilha Cinzenta',text:'Um caçador da lua aprende a distinguir troféu de alimento. A carne fresca pode ser vendida, mas nas cidades é curada com madeira e convertida em provisões duráveis para a Casa. Peles aquecem vigias, pagam dívidas e atravessam fronteiras onde moedas perdem valor. A habilidade do mestre de caça nasce de preparar cada presa e conhecer os caminhos de seu habitat. A matilha que alimenta a cidade ganha tempo para defender seus postos.'},
 {id:'sigils',act:'IV · Sob a Pedra',title:'Os dois selos',hint:'Entre em uma dungeon.',voice:'Inscrição na entrada das criptas',text:'Sob cada região existem câmaras que precedem as Casas. Dois selos prendem o guardião mais fundo; ambos respondem apenas depois que outros vigias caem. O primeiro selo representa memória, o segundo escolha. Abrir um sem o outro deixa o coração da cripta fechado. Expedições podem se ajudar ou disputar o mesmo corredor, mas o tesouro reconhece cada viajante uma única vez. Os corredores permanecem por um tempo antes de a pedra refazer o seu desenho.'},
 {id:'veil',act:'IV · Sob a Pedra',title:'O coração do Véu',hint:'Derrote um chefe ou colosso.',voice:'Fragmento do Oráculo',text:'O Véu não é uma criatura; é o resto de um juramento capaz de dar forma ao medo. Colossos aparecem onde guerra, mineração e ritos se repetem até ferir a terra. Seu sangue e sua essência não pertencem a uma só linhagem, e por isso raids reúnem inimigos políticos diante de uma ameaça comum. Cada vitória fecha uma fissura por pouco tempo. Os sábios suspeitam que a fonte verdadeira ainda pulsa além das treze terras conhecidas.'},
 {id:'war',act:'V · A Lua Vermelha',title:'A guerra que escolhe herdeiros',hint:'Participe de uma guerra ou cerco entre Casas.',voice:'Crônica da Última Bandeira',text:'Toda conquista resolve uma fome e cria outra. Um posto tomado muda a influência no mapa; uma cidade destruída desloca artesãos, guardas e comerciantes. A política das Casas decide quem pode vender, construir e atravessar estradas sob escolta. Os mais sábios chamam isso de ecossistema; quem perdeu uma casa chama de inverno. A lua vermelha retorna quando ambição e sobrevivência se tornam indistinguíveis, e Véspera exige que cada personagem arque com as consequências de sua bandeira.'},
 {id:'karma',act:'V · A Lua Vermelha',title:'A marca que se vê',hint:'Abra a Crônica de Sangue e siga sua caçada.',voice:'Livro da Vigília',text:'Karma não mede bondade. Ele registra quanto da noite uma pessoa conseguiu dobrar à própria vontade. Sequências de abates acendem um rastro passageiro; patentes levam muito mais tempo para ser conquistadas e não somem quando o brilho cessa. Assassinatos de viajantes fora da guerra deixam marcas que a Vigília sabe ler e recompensas que outros caçadores podem cobrar. O branco recorda o começo, o vermelho anuncia a fome, o preto revela o custo, e o ouro carrega o peso de ser reconhecido por todos.'},
 {id:'tomorrow',act:'VI · Amanhã',title:'A terceira escolha',hint:'Reúna histórias pelo mundo.',voice:'Última página ainda incompleta',text:'O enredo de Véspera não tem um último rei escrito de antemão. Cada cidade construída, fonte esgotada, criatura libertada, contrato cumprido e guerra vencida altera o que as próximas caravanas encontrarão. A Vigília acredita que a ruptura da primeira lua pode ser selada; as Casas preferem aprender a controlá-la. Há uma terceira escolha, guardada nas lembranças dos errantes: deixar que o mundo responda a quem vive nele, sem coroas sobre o céu. Nenhum cronista sabe se isso salvará Véspera. Essa página só pode ser escrita por seus viajantes.'}
]);
const byId=new Map(VESPERA_CHRONICLE.map(entry=>[entry.id,entry]));
export function ensureLore(p){const r=p.realm;r.lore||={unlocked:['oath'],read:[],latest:'oath'};r.lore.unlocked||=['oath'];r.lore.read||=[];return r.lore;}
export function recordLore(p,id){const entry=byId.get(id);if(!entry)return false;const lore=ensureLore(p);if(lore.unlocked.includes(id))return false;lore.unlocked.push(id);lore.latest=id;if(lore.unlocked.length>=9&&!lore.unlocked.includes('tomorrow')){lore.unlocked.push('tomorrow');lore.latest='tomorrow';}return true;}
export function loreView(p){const lore=ensureLore(p);return {latest:lore.latest,read:lore.read,unlocked:lore.unlocked};}
export function loreAction(p,input){const lore=ensureLore(p);check(lore.unlocked.includes(input.entryId),'Esta página ainda precisa ser descoberta no mundo.');check(byId.has(input.entryId),'Página desconhecida.');if(!lore.read.includes(input.entryId))lore.read.push(input.entryId);return {message:`Crônica aberta: ${byId.get(input.entryId).title}.`};}
